import { useEffect, useState } from 'react';
import { ListPlus, Plus, Save, Trash2, Users, WalletCards } from 'lucide-react';
import { Table } from '../../shared/ui';
import { money, useStoredState } from '../../shared/utils';

type ExpenseTab='vendors'|'expenses'|'categories';
export type VendorRow=[string,string,string,string,string,string];
export type ExpenseRow=[string,string,string,string,string,string,string,string,string];
export type CategoryRow=[string,string,string];

export const defaultVendors:VendorRow[]=[];
export const defaultExpenses:ExpenseRow[]=[];
export const defaultCategories:CategoryRow[]=[['CAT-001','Material Purchase','Fabric and garment materials'],['CAT-002','Accessories Purchase','Buttons, zip, thread and accessories'],['CAT-003','Staff Refreshments','Tea, snacks and staff refreshments'],['CAT-004','Transport / Diesel','Delivery fuel and transport charges'],['CAT-005','Electricity','Electricity and utility charges'],['CAT-006','Shop Rent','Shop, office or factory rent'],['CAT-007','Repairs & Maintenance','Machine and premises maintenance'],['CAT-008','Office Expenses','Printing, stationery and administration'],['CAT-009','Other Expense','Other business expenses']];

export function ExpensesPage(){
  const [tab,setTab]=useState<ExpenseTab>('vendors');
  const [showExpenseForm,setShowExpenseForm]=useState(false);
  const [vendors,setVendors]=useStoredState<VendorRow[]>('garment-expense-vendors',defaultVendors);
  const [expenses,setExpenses]=useStoredState<ExpenseRow[]>('garment-expenses',defaultExpenses);
  const [categories,setCategories]=useStoredState<CategoryRow[]>('garment-expense-categories',defaultCategories);
  useEffect(()=>{if(!categories.length)setCategories(defaultCategories)},[categories.length,setCategories]);
  const [vendorForm,setVendorForm]=useState({name:'',type:'Dress Supply',contact:'',phone:'',gst:''});
  const [categoryForm,setCategoryForm]=useState({code:'',name:'',description:''});
  const [expenseForm,setExpenseForm]=useState({vendor:'',paidTo:'',year:(()=>{const now=new Date();const y=now.getFullYear();return `${y}-${String((y+1)%100).padStart(2,'0')}`})(),type:categories[0]?.[1]||'',description:'',date:new Date().toISOString().slice(0,10),amount:0,mode:'Cash',bill:''});

  useEffect(()=>{if(categories.length&&!categories.some(category=>category[1]===expenseForm.type))setExpenseForm(current=>({...current,type:categories[0][1]}))},[categories,expenseForm.type]);

  const addVendor=()=>{if(!vendorForm.name.trim())return;setVendors(current=>[[`VEN-${String(current.length+101)}`,vendorForm.name.trim(),vendorForm.type,vendorForm.contact||'-',vendorForm.phone||'-',vendorForm.gst||'-'],...current]);setVendorForm({name:'',type:'Dress Supply',contact:'',phone:'',gst:''})};
  const addCategory=()=>{const name=categoryForm.name.trim();if(!name)return;const code=categoryForm.code.trim()||`CAT-${String(categories.length+1).padStart(3,'0')}`;const exists=categories.some(category=>category[0].toLowerCase()===code.toLowerCase()||category[1].toLowerCase()===name.toLowerCase());if(exists){window.alert('This category code or category name already exists.');return}setCategories(current=>[...current,[code,name,categoryForm.description.trim()||'-']]);setExpenseForm(current=>({...current,type:name}));setCategoryForm({code:'',name:'',description:''})};
  const deleteCategory=(category:CategoryRow)=>{const used=expenses.some(expense=>expense[3]===category[1]);if(used){window.alert(`${category[1]} is already used in expense entries. Keep it in Category Head for history.`);return}if(!window.confirm(`Delete expense category ${category[1]}?`))return;setCategories(current=>current.filter(row=>row[0]!==category[0]))};
  const addExpense=()=>{if(expenseForm.amount<=0||!expenseForm.type)return;setExpenses(current=>[[`EXP-${String(current.length+1001)}`,expenseForm.vendor||expenseForm.paidTo||'-',expenseForm.year,expenseForm.type,expenseForm.description||'-',expenseForm.date,money(expenseForm.amount),expenseForm.mode,expenseForm.bill||'-'],...current]);setExpenseForm({...expenseForm,amount:0,description:'',bill:'',paidTo:''});setShowExpenseForm(false)};
  const categoryOptions=categories.map(category=><option key={category[0]} value={category[1]}>{category[1]}</option>);

  return <section className="content">
    <div className="measurement-tabs wage-tabs">
      <button className={tab==='vendors'?'active':''} onClick={()=>setTab('vendors')}><Users size={16}/><span>Vendor List<small>{vendors.length} vendors</small></span></button>
      <button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}><WalletCards size={16}/><span>Expenses<small>{expenses.length} entries</small></span></button>
      <button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}><ListPlus size={16}/><span>Category Head<small>{categories.length} categories</small></span></button>
    </div>
    {tab==='vendors'&&<><article className="card measurement-form"><div className="form-title"><div><h2>Add vendor</h2><p>Vendor master for expenses and material purchases.</p></div></div><div className="form-grid"><label>Vendor name<input value={vendorForm.name} onChange={e=>setVendorForm({...vendorForm,name:e.target.value})}/></label><label>Type<input value={vendorForm.type} onChange={e=>setVendorForm({...vendorForm,type:e.target.value})}/></label><label>Contact<input value={vendorForm.contact} onChange={e=>setVendorForm({...vendorForm,contact:e.target.value})}/></label><label>Phone<input value={vendorForm.phone} onChange={e=>setVendorForm({...vendorForm,phone:e.target.value})}/></label><label>GST No<input value={vendorForm.gst} onChange={e=>setVendorForm({...vendorForm,gst:e.target.value})}/></label></div><div className="form-actions"><button className="primary" onClick={addVendor}><Plus size={16}/> Add vendor</button></div></article><Table title="Vendor list" copy="Expense and purchase vendor master" headers={['CODE','VENDOR NAME','TYPE','CONTACT','PHONE','GST NO']} rows={vendors}/></>}
    {tab==='expenses'&&<>{!showExpenseForm&&<><div className="filterbar salary-filter"><label>Search<input placeholder="Expense, vendor, bill no"/></label><label>Expense category<select><option>All</option>{categoryOptions}</select></label><button className="primary" onClick={()=>setShowExpenseForm(true)}><Plus size={16}/> Add expense</button></div><Table title="Expense list" copy="Vendor-wise and daily expenses" headers={['EXP CODE','VENDOR / PAID TO','YEAR','TYPE','DESCRIPTION','DATE','AMOUNT','MODE','BILL NO']} rows={expenses}/></>}{showExpenseForm&&<article className="card measurement-form"><div className="form-title"><div><h2>Add expense</h2><p>Select category from Category Head and add the expense amount.</p></div><button className="outline" onClick={()=>setShowExpenseForm(false)}>Back to list</button></div><div className="form-grid"><label>Date<input type="date" value={expenseForm.date} onChange={e=>setExpenseForm({...expenseForm,date:e.target.value})}/></label><label>Expense category<select value={expenseForm.type} onChange={e=>setExpenseForm({...expenseForm,type:e.target.value})}>{categoryOptions}</select></label><label>Vendor optional<select value={expenseForm.vendor} onChange={e=>setExpenseForm({...expenseForm,vendor:e.target.value})}><option value="">No vendor</option>{vendors.map(v=><option key={v[0]}>{v[1]}</option>)}</select></label><label>Paid to / Person<input value={expenseForm.paidTo} onChange={e=>setExpenseForm({...expenseForm,paidTo:e.target.value})} placeholder="Optional"/></label><label>Amount<input type="number" min="0" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:Number(e.target.value)})}/></label><label>Payment mode<select value={expenseForm.mode} onChange={e=>setExpenseForm({...expenseForm,mode:e.target.value})}><option>Cash</option><option>UPI</option><option>Bank</option></select></label><label>Year<input value={expenseForm.year} onChange={e=>setExpenseForm({...expenseForm,year:e.target.value})}/></label><label>Bill No<input value={expenseForm.bill} onChange={e=>setExpenseForm({...expenseForm,bill:e.target.value})} placeholder="Optional"/></label><label className="wide">Remarks / Description<input value={expenseForm.description} onChange={e=>setExpenseForm({...expenseForm,description:e.target.value})} placeholder="Example: tea for staff, diesel for delivery"/></label></div><div className="form-actions"><button className="outline" onClick={()=>setShowExpenseForm(false)}>Cancel</button><button className="primary" onClick={addExpense}><Plus size={16}/> Save expense</button></div></article>}</>}
    {tab==='categories'&&<div className="masters-grid"><article className="card measurement-form"><div className="form-title"><div><h2>Category head</h2><p>Add expense categories once. They will appear in Add Expense and filter dropdowns.</p></div></div><div className="form-grid"><label>Category code<input value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})} placeholder="Example: CAT-008"/></label><label>Category name<input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} placeholder="Example: Needle purchase"/></label><label className="wide">Description<input value={categoryForm.description} onChange={e=>setCategoryForm({...categoryForm,description:e.target.value})} placeholder="Optional"/></label></div><div className="form-actions"><button className="primary" onClick={addCategory}><Save size={16}/> Save category</button></div></article><article className="card jobs module-table"><div className="cardhead"><div><h2>Category head list</h2><p>These categories are used in expense entry.</p></div></div><table><thead><tr><th>CODE</th><th>CATEGORY</th><th>DESCRIPTION</th><th>ACTION</th></tr></thead><tbody>{categories.map(category=><tr key={category[0]}><td><strong>{category[0]}</strong></td><td>{category[1]}</td><td>{category[2]}</td><td><button className="danger-btn" onClick={()=>deleteCategory(category)}><Trash2 size={14}/> Delete</button></td></tr>)}</tbody></table></article></div>}
  </section>;
}
