import { useState } from 'react';
import { BarChart3, Printer, ReceiptText, Save, Users, WalletCards } from 'lucide-react';
import { defaultWorkTypes } from '../../shared/defaults';
import type { AdvanceEntry, Assignment, Employee, Invoice, InvoicePayment, SalaryPayment, WorkEntry, WorkType } from '../../shared/types';
import { PrintPreview, Table } from '../../shared/ui';
import { money, useStoredState, workTypeCode } from '../../shared/utils';
const nameOf=(employees:Employee[],id:string)=>employees.find(e=>e.id===id)?.name||'-';
const customerName=(customers:string[][],id:string)=>customers.find(c=>c[0]===id)?.[1]||'-';

export function ReportsPage({employees,workTypes,advances,workEntries,assignments,customers}:{employees:Employee[];workTypes:WorkType[];advances:AdvanceEntry[];workEntries:WorkEntry[];assignments:Assignment[];customers:string[][]}){
  const [tab,setTab]=useState<'overview'|'income'|'expense'|'staff'>('overview');
  const [year,setYear]=useState(()=>{const now=new Date();const y=now.getFullYear();return `${y}-${String((y+1)%100).padStart(2,'0')}`});
  const [from,setFrom]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`});
  const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const [incomeType,setIncomeType]=useState('All');
  const [expenseType,setExpenseType]=useState('All');
  const [mode,setMode]=useState('All');
  const [staffEmployee,setStaffEmployee]=useState('All');
  const [showReportPrint,setShowReportPrint]=useState(false);
  const [invoices,setInvoices]=useStoredState<Invoice[]>('garment-invoices',[]);
  const [payments,setPayments]=useStoredState<InvoicePayment[]>('garment-invoice-payments',[]);
  const [schoolCollections,setSchoolCollections]=useStoredState<string[][]>('garment-school-collections',[]);
  const [expenses,setExpenses]=useStoredState<string[][]>('garment-expenses',[]);
  const [salaryHistory,setSalaryHistory]=useStoredState<SalaryPayment[]>('garment-salary-history',[]);
  const parseMoney=(value:string)=>Number((value.match(/\d[\d,]*(?:\.\d+)?/)?.[0]||'0').replace(/,/g,''));
  const incomeEntries:{date:string;type:string;ref:string;party:string;description:string;mode:string;amount:number}[]=[
    ...payments.map(p=>{const inv=invoices.find(i=>i.invoiceNo===p.invoiceNo);return {date:p.date,type:'Tax Invoice',ref:p.invoiceNo,party:p.customer,description:inv?inv.product:'Invoice payment',mode:p.mode,amount:p.amount}}),
    ...schoolCollections.map(row=>({date:row[1],type:'School Collection',ref:row[0],party:row[2],description:'School collection',mode:row[3],amount:parseMoney(row[4])})),
  ];
  const expenseEntries:{date:string;type:string;ref:string;party:string;description:string;mode:string;amount:number}[]=[
    ...expenses.map(row=>({date:row[5],type:row[3],ref:row[0],party:row[1],description:row[4]==='-'?'Expense':row[4],mode:row[7],amount:parseMoney(row[6])})),
    ...salaryHistory.map(sp=>({date:sp.paidDate,type:'Staff Salary',ref:sp.id,party:nameOf(employees,sp.employeeId),description:`Salary ${sp.from} to ${sp.to}`,mode:sp.mode,amount:sp.netPayable})),
  ];
  const dateFilter=(row:{date:string})=>row.date>=from&&row.date<=to;
  const visibleIncome=incomeEntries.filter(row=>dateFilter(row)&&(incomeType==='All'||row.type===incomeType)&&(mode==='All'||row.mode===mode));
  const visibleExpenses=expenseEntries.filter(row=>dateFilter(row)&&(expenseType==='All'||row.type===expenseType)&&(mode==='All'||row.mode===mode));
  const incomeTotal=visibleIncome.reduce((sum,row)=>sum+row.amount,0);
  const expenseTotal=visibleExpenses.reduce((sum,row)=>sum+row.amount,0);
  const net=incomeTotal-expenseTotal;
  const schoolIncome=visibleIncome.filter(i=>i.type==='School Collection').reduce((a,b)=>a+b.amount,0);
  const invoiceIncome=visibleIncome.filter(i=>i.type==='Tax Invoice').reduce((a,b)=>a+b.amount,0);
  const customerStitchingIncome=visibleIncome.filter(i=>i.type==='Customer Stitching Income').reduce((a,b)=>a+b.amount,0);
  const staffExpense=visibleExpenses.filter(e=>e.type==='Staff Salary').reduce((a,b)=>a+b.amount,0);
  const vendorExpense=visibleExpenses.filter(e=>e.type!=='Staff Salary').reduce((a,b)=>a+b.amount,0);
  const incomeAggregates=Object.values(visibleIncome.reduce((acc,row)=>{acc[row.type]=acc[row.type]||{type:row.type,amount:0};acc[row.type].amount+=row.amount;return acc},{} as Record<string,{type:string;amount:number}>));
  const expenseAggregates=Object.values(visibleExpenses.reduce((acc,row)=>{acc[row.type]=acc[row.type]||{type:row.type,amount:0};acc[row.type].amount+=row.amount;return acc},{} as Record<string,{type:string;amount:number}>));
  const clearFilters=()=>{const now=new Date();setIncomeType('All');setExpenseType('All');setMode('All');setFrom(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`);setTo(now.toISOString().slice(0,10))};
  const workTypeName=(id:string)=>{const wt=workTypes.find(x=>x.id===id)||defaultWorkTypes.find(x=>x.id===id);return wt?`${workTypeCode(wt)} - ${wt.name}`:'-'};
  const workTypeRate=(id:string)=>{const wt=workTypes.find(x=>x.id===id)||defaultWorkTypes.find(x=>x.id===id);return wt?.rate||0};
  const periodAssignments=assignments.filter(a=>dateFilter(a));
  const periodWorkEntries=workEntries.filter(w=>dateFilter(w));
  const periodAdvances=advances.filter(a=>dateFilter(a));
  const assignedPcs=periodAssignments.reduce((s,a)=>s+a.works.reduce((x,w)=>x+w.qty,0),0);
  const completedPcs=periodAssignments.reduce((s,a)=>s+a.works.reduce((x,w)=>x+Math.min(w.done,w.qty),0),0);
  const staffRows=employees.map(e=>{const cuts=periodAssignments.filter(a=>a.employeeId===e.id);const assigned=cuts.reduce((s,a)=>s+a.works.reduce((x,w)=>x+w.qty,0),0);const done=cuts.reduce((s,a)=>s+a.works.reduce((x,w)=>x+Math.min(w.done,w.qty),0),0);const entries=periodWorkEntries.filter(w=>w.employeeId===e.id);const entryPcs=entries.reduce((s,w)=>s+w.quantity,0);const entryAmount=entries.reduce((s,w)=>{const wt=workTypes.find(x=>x.id===w.workTypeId)||defaultWorkTypes.find(x=>x.id===w.workTypeId);return s+w.quantity*(wt?.rate||0)},0);const adv=periodAdvances.filter(a=>a.employeeId===e.id).reduce((s,a)=>s+a.amount,0);return {id:e.id,name:e.name,cuts:cuts.length,assigned,done,entryPcs,entryAmount,adv}});
  const filteredEntries=periodWorkEntries.filter(w=>staffEmployee==='All'||w.employeeId===staffEmployee);
  const entryAggregates=workTypes.map(wt=>{const rows=filteredEntries.filter(w=>w.workTypeId===wt.id);const qty=rows.reduce((s,w)=>s+w.quantity,0);return {name:workTypeName(wt.id),qty,rate:workTypeRate(wt.id),amount:qty*workTypeRate(wt.id)}}).filter(x=>x.qty>0);
  const staffCuttingRows=periodAssignments.filter(a=>staffEmployee==='All'||a.employeeId===staffEmployee);
  const filteredStaffRows=staffRows.filter(r=>staffEmployee==='All'||r.id===staffEmployee);
  const staffTotalRow=filteredStaffRows.reduce((acc,r)=>({cuts:acc.cuts+r.cuts,assigned:acc.assigned+r.assigned,done:acc.done+r.done,entryPcs:acc.entryPcs+r.entryPcs,entryAmount:acc.entryAmount+r.entryAmount,adv:acc.adv+r.adv}),{cuts:0,assigned:0,done:0,entryPcs:0,entryAmount:0,adv:0});
  const filterBar=<div className="filterbar report-filter no-print"><label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option>2026-27</option><option>2025-26</option></select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="outline" onClick={clearFilters}>Clear Filters</button>{tab==='income'&&<label>Category<select value={incomeType} onChange={e=>setIncomeType(e.target.value)}><option>All</option><option>School Collection</option><option>Tax Invoice</option><option>Customer Stitching Income</option></select></label>}{tab==='expense'&&<label>Expense Type<select value={expenseType} onChange={e=>setExpenseType(e.target.value)}><option>All</option><option>Vendor Expense</option><option>Staff Salary</option><option>Tea for employee</option><option>Diesel</option></select></label>}{tab==='staff'&&<label>Employee<select value={staffEmployee} onChange={e=>setStaffEmployee(e.target.value)}><option value="All">All staff</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>}{tab!=='overview'&&<label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>All</option><option>Cash</option><option>UPI</option><option>Bank</option></select></label>}<button className="primary" onClick={()=>setShowReportPrint(true)}><Save size={16}/> Export</button></div>;
  const reportDoc=<div className="tax-doc"><h1>{tab==='income'?'INCOME DETAILS':tab==='expense'?'EXPENSE DETAILS':tab==='staff'?'STAFF PRODUCTION & SALARY':'INCOME VS EXPENDITURE'}</h1><div className="preview-meta"><span>Period: {from} to {to}</span><span>Year: {year}</span><span>{tab==='income'?'Income':tab==='expense'?'Expense':'Net'}: {money(tab==='income'?incomeTotal:tab==='expense'?expenseTotal:net)}</span></div>{tab==='overview'&&<div className="report-summary-cards"><div className="report-card blue"><span>Income</span><strong>{money(incomeTotal)}</strong></div><div className="report-card coral"><span>Expenditure</span><strong>{money(expenseTotal)}</strong></div><div className={net>=0?'report-card green':'report-card red'}><span>{net>=0?'Net Profit':'Net Deficit'}</span><strong>{money(Math.abs(net))}</strong></div></div>}<table className="doc-table">{tab==='income'?<><thead><tr><th>DATE</th><th>REFERENCE</th><th>SCHOOL / CUSTOMER</th><th>CATEGORY</th><th>DESCRIPTION</th><th>MODE</th><th>AMOUNT</th></tr></thead><tbody>{visibleIncome.map((row,i)=><tr key={i}><td>{row.date}</td><td>{row.ref}</td><td>{row.party}</td><td>{row.type}</td><td>{row.description}</td><td>{row.mode}</td><td>{money(row.amount)}</td></tr>)}</tbody></>:tab==='expense'?<><thead><tr><th>DATE</th><th>EXPENSE TYPE</th><th>REFERENCE</th><th>STAFF / VENDOR</th><th>DESCRIPTION</th><th>MODE</th><th>AMOUNT</th></tr></thead><tbody>{visibleExpenses.map((row,i)=><tr key={i}><td>{row.date}</td><td>{row.type}</td><td>{row.ref}</td><td>{row.party}</td><td>{row.description}</td><td>{row.mode}</td><td>{money(row.amount)}</td></tr>)}</tbody></>:tab==='staff'?<><thead><tr><th>STAFF</th><th>CUTTINGS</th><th>ASSIGNED PCS</th><th>DONE PCS</th><th>ENTRY PCS</th><th>ENTRY AMOUNT</th><th>ADVANCE</th></tr></thead><tbody>{filteredStaffRows.map(r=><tr key={r.id}><td>{r.name}</td><td>{String(r.cuts)}</td><td>{String(r.assigned)}</td><td>{String(r.done)}</td><td>{String(r.entryPcs)}</td><td>{money(r.entryAmount)}</td><td>{money(r.adv)}</td></tr>)}</tbody></>:<><thead><tr><th>CATEGORY</th><th>AMOUNT</th></tr></thead><tbody>{incomeAggregates.map(row=><tr key={row.type}><td>{row.type}</td><td>{money(row.amount)}</td></tr>)}</tbody></>}</table><div className="doc-footer"><div><b>Total</b><p>{money(tab==='income'?incomeTotal:tab==='expense'?expenseTotal:net)}</p></div><div><h3>Authorized Signatory</h3><span>Garment Production ERP</span></div></div></div>;
  return <section className="content reports-page finance-reports"><div className="measurement-tabs wage-tabs report-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><BarChart3 size={16}/><span>Income vs Expenditure<small>profit and deficit</small></span></button><button className={tab==='income'?'active':''} onClick={()=>setTab('income')}><ReceiptText size={16}/><span>Income Details<small>collections</small></span></button><button className={tab==='expense'?'active':''} onClick={()=>setTab('expense')}><WalletCards size={16}/><span>Expense Details<small>spend ledger</small></span></button><button className={tab==='staff'?'active':''} onClick={()=>setTab('staff')}><Users size={16}/><span>Staff Production & Salary<small>assignments + wages</small></span></button></div>
    {tab==='overview'&&<div className="report-summary-cards"><div className="report-card blue"><span>Income</span><strong>{money(incomeTotal)}</strong><small>{visibleIncome.length} entries</small></div><div className="report-card coral"><span>Expenditure</span><strong>{money(expenseTotal)}</strong><small>{visibleExpenses.length} entries</small></div><div className={net>=0?'report-card green':'report-card red'}><span>{net>=0?'Net Profit':'Net Deficit'}</span><strong>{money(Math.abs(net))}</strong><small>{incomeTotal?Math.round((Math.abs(net)/incomeTotal)*100):0}% of income</small></div><div className="report-card purple"><span>Staff Work Amount</span><strong>{money(workEntries.reduce((sum,w)=>{const wt=workTypes.find(x=>x.id===w.workTypeId)||defaultWorkTypes.find(x=>x.id===w.workTypeId);return sum+w.quantity*(wt?.rate||0)},0))}</strong><small>{employees.length} staff</small></div></div>}
    {filterBar}
    {tab==='overview'&&<><div className="report-grid"><Table title="Income Categories" copy="School collection and other income sources with collected amounts" headers={['CATEGORY','AMOUNT']} rows={incomeAggregates.map(row=>[row.type,money(row.amount)])}/><Table title="Expenditure Categories" copy="Expense categories with amounts" headers={['CATEGORY','AMOUNT']} rows={expenseAggregates.map(row=>[row.type,money(row.amount)])}/></div><div className="net-row">Total Income Collected: <b className="inc">{money(incomeTotal)}</b><i>•</i>Total Expenditure: <b className="exp">{money(expenseTotal)}</b><i>•</i>Net Surplus: <b className={net>=0?'sur':'def'}>{money(net)}</b></div></>}
    {tab==='income'&&<><div className="detail-summary-strip"><div className="report-card green"><span>Total Income</span><strong>{money(incomeTotal)}</strong></div><div className="report-card blue"><span>Entries</span><strong>{String(visibleIncome.length)}</strong></div><div className="report-card purple"><span>School Collection</span><strong>{money(schoolIncome)}</strong></div><div className="report-card orange"><span>Tax Invoice</span><strong>{money(invoiceIncome)}</strong></div></div><Table title="Income details" copy="School, invoice and stitching income ledger" headers={['DATE','REFERENCE','SCHOOL / CUSTOMER','CATEGORY','DESCRIPTION','MODE','AMOUNT']} rows={visibleIncome.map(row=>[row.date,row.ref,row.party,row.type,row.description,row.mode,money(row.amount)])}/></>}
    {tab==='expense'&&<><div className="detail-summary-strip"><div className="report-card coral"><span>Total Expense</span><strong>{money(expenseTotal)}</strong></div><div className="report-card blue"><span>Entries</span><strong>{String(visibleExpenses.length)}</strong></div><div className="report-card purple"><span>Staff Salary</span><strong>{money(staffExpense)}</strong></div><div className="report-card orange"><span>Vendor Expense</span><strong>{money(vendorExpense)}</strong></div></div><Table title="Expense details" copy="Vendor, staff salary and daily expense ledger" headers={['DATE','EXPENSE TYPE','REFERENCE','STAFF / VENDOR','DESCRIPTION','MODE','AMOUNT']} rows={visibleExpenses.map(row=>[row.date,row.type,row.ref,row.party,row.description,row.mode,money(row.amount)])}/></>}
    {tab==='staff'&&<>
      <div className="report-summary-cards"><div className="report-card blue"><span>Assignments</span><strong>{periodAssignments.length}</strong><small>{staffEmployee==='All'?'all staff':employees.find(e=>e.id===staffEmployee)?.name}</small></div><div className="report-card purple"><span>Pieces Assigned</span><strong>{assignedPcs}</strong><small>across cuttings</small></div><div className="report-card green"><span>Pieces Completed</span><strong>{completedPcs}</strong><small>{assignedPcs?Math.round(completedPcs/assignedPcs*100):0}% done</small></div><div className="report-card orange"><span>Work Amount</span><strong>{money(periodWorkEntries.reduce((s,w)=>{const wt=workTypes.find(x=>x.id===w.workTypeId)||defaultWorkTypes.find(x=>x.id===w.workTypeId);return s+w.quantity*(wt?.rate||0)},0))}</strong><small>from wage entries</small></div></div>
      <div className="report-grid">
        <Table title="Staff production & salary" copy="Cuttings assigned, pieces done and wage entry amounts per staff member" headers={['STAFF','CUTTINGS','ASSIGNED PCS','DONE PCS','ENTRY PCS','ENTRY AMOUNT','ADVANCE']} rows={[...filteredStaffRows.map(r=>[r.name,String(r.cuts),String(r.assigned),String(r.done),String(r.entryPcs),money(r.entryAmount),money(r.adv)] as string[]),['Total',String(staffTotalRow.cuts),String(staffTotalRow.assigned),String(staffTotalRow.done),String(staffTotalRow.entryPcs),money(staffTotalRow.entryAmount),money(staffTotalRow.adv)] as string[]]}/>
        <Table title="Work type production" copy="Work-type-wise quantity and amount from wage entries" headers={['WORK TYPE','QTY','RATE','AMOUNT']} rows={entryAggregates.map(x=>[x.name,String(x.qty),money(x.rate),money(x.amount)])}/>
      </div>
      <Table title="Cutting-wise detail" copy="Each cutting with its works and done / assigned progress" headers={['CUTTING','DATE','CUSTOMER','STAFF','WORK','WORK TYPE','DONE / ASSIGNED','AMOUNT']} rows={staffCuttingRows.flatMap(a=>a.works.map((w,i)=>[a.cuttingNo,a.date,customerName(customers,a.customerId),nameOf(employees,a.employeeId),`Work ${i+1}`,workTypeName(w.workTypeId),`${Math.min(w.done,w.qty)} / ${w.qty}`,money(Math.min(w.done,w.qty)*workTypeRate(w.workTypeId))]))}/>
    </>}
  {showReportPrint&&<PrintPreview doc={reportDoc} onClose={()=>setShowReportPrint(false)}/>}
  </section>
}
