import type React from 'react';
import { useEffect, useState } from 'react';
import { AlertTriangle, Factory, IndianRupee, Printer, Save, Scissors, Users } from 'lucide-react';
import type { CompanySettings } from '../modules/settings/SettingsPage';
import { printPage, savePdf } from './utils';

export function Title({title,copy}:{title:string,copy:string}){return <div className="welcome"><div><p>GARMENT PRODUCTION ERP</p><h1>{title}</h1><span>{copy}</span></div></div>}
export function Stats({values}:{values:string[][]}){const icons=[<Users/>,<Scissors/>,<IndianRupee/>,<AlertTriangle/>];return <div className="metrics">{values.map((v,i)=><Metric key={v[0]} title={v[0]} value={v[1]} note={v[2]} icon={icons[i]} tone={['blue','purple','green','orange'][i]}/>)}</div>}
export function Table({title,copy,headers,rows,actions,paged=false}:{title:string;copy:string;headers:string[];rows:string[][];actions?:(row:string[])=>React.ReactNode;paged?:boolean}){
  const [page,setPage]=useState(1);
  const [pageSize,setPageSize]=useState(5);
  const pageCount=Math.max(1,Math.ceil(rows.length/pageSize));
  const safePage=Math.min(page,pageCount);
  const visible=paged?rows.slice((safePage-1)*pageSize,safePage*pageSize):rows;
  useEffect(()=>{setPage(current=>Math.min(current,pageCount))},[pageCount]);
  return <article className="card jobs module-table"><div className="cardhead"><div><h2>{title}</h2><p>{copy}</p></div><input className="smallsearch" placeholder="Search..."/></div><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}{actions&&<th>ACTIONS</th>}</tr></thead><tbody>{visible.map(r=><tr key={r[0]}>{r.map((x,i)=>x.startsWith('data:image/')?<td key={i}><img className="table-thumb" src={x} alt=""/></td>:<td key={i}>{i===0?<strong>{x}</strong>:['Present','Completed','In Progress','Pending','Leave'].includes(x)?<span className={'status '+x.toLowerCase().replace(' ','-')}>{x}</span>:x}</td>)}{actions&&<td>{actions(r)}</td>}</tr>)}</tbody></table>{paged&&<div className="table-footer paginated-footer"><span>Showing {rows.length?((safePage-1)*pageSize)+1:0}-{Math.min(safePage*pageSize,rows.length)} of {rows.length} entries</span><div className="pager"><label>Rows<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={5}>5</option><option value={10}>10</option><option value={20}>20</option></select></label><button className="outline" disabled={safePage===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Prev</button><span>Page {safePage} / {pageCount}</span><button className="outline" disabled={safePage===pageCount} onClick={()=>setPage(p=>Math.min(pageCount,p+1))}>Next</button></div></div>}</article>}
export function Placeholder({title}:{title:string}){return <section className="content"><Title title={title} copy="This module is planned for the next implementation phase."/><article className="card empty"><Factory/><h2>{title}</h2><p>The module shell is ready.</p></article></section>}
export function Metric({title,value,note,icon,tone}:{title:string,value:string,note:string,icon:React.ReactNode,tone:string}){return <article className="metric"><div className={'metricicon '+tone}>{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{note}</small></div></article>}
export function CompanyPrintHeader({company}:{company:CompanySettings}){return <div className="doc-company company-print-header"><img src="./threadflow-logo.png" alt="Teli ThreadFlow ERP logo"/><div><h2>Teli ThreadFlow ERP</h2><p>{company.name||'Garment Name'}</p>{company.address&&<p>{company.address}</p>}<p>{company.gst&&`GSTIN: ${company.gst}`}{company.gst&&company.phone?' | ':''}{company.phone&&`Phone: ${company.phone}`}</p></div></div>}
export function CompanyReceiptHeader({company}:{company:CompanySettings}){return <div className="full-row receipt-company company-receipt-header">{company.logo&&<img src={company.logo} alt="Garment logo"/>}<div><strong>{company.name||'Garment'}</strong><span>{company.gst&&`GST / GT: ${company.gst}`}{company.gst&&company.phone?' | ':''}{company.phone&&`Phone: ${company.phone}`}</span>{company.address&&<small>{company.address}</small>}</div></div>}
export function PrintPreview({doc,onClose,extra}:{doc:React.ReactNode;onClose:()=>void;extra?:React.ReactNode}){return <div className="print-preview-overlay"><div className="print-preview-shell invoice-preview"><div className="preview-actions"><button className="primary" onClick={printPage}><Printer size={16}/> Print</button><button className="outline" onClick={()=>savePdf()}><Save size={16}/> Save PDF</button>{extra}<button className="outline" onClick={onClose}>Cancel</button></div>{doc}</div></div>}
