import { Fragment, useEffect, useState } from 'react';
import type React from 'react';
import { BarChart3, ClipboardList, Eye, Pencil, Plus, Printer, Trash2 } from 'lucide-react';
import { PrintPreview, Stats, Table } from '../../shared/ui';
import { money, workTypeCode } from '../../shared/utils';
import type { Assignment, AssignmentWork, Employee, WorkType } from '../../shared/types';
import { defaultWorkTypes } from '../../shared/defaults';

type Status='Pending'|'In Progress'|'Completed';
const statusOf=(a:Assignment):Status=>a.works.length&&a.works.every(w=>w.done>=w.qty)?'Completed':a.works.some(w=>w.done>0)?'In Progress':'Pending';
const workTotal=(a:Assignment)=>a.works.reduce((s,w)=>s+w.qty,0);
const workDone=(a:Assignment)=>a.works.reduce((s,w)=>s+Math.min(w.done,w.qty),0);
const workAmount=(a:Assignment,workTypes:WorkType[])=>a.works.reduce((s,w)=>{const wt=workTypes.find(x=>x.id===w.workTypeId)||defaultWorkTypes.find(x=>x.id===w.workTypeId);return s+w.qty*(wt?.rate||0)},0);
const earnedAmount=(a:Assignment,workTypes:WorkType[])=>a.works.reduce((s,w)=>{const wt=workTypes.find(x=>x.id===w.workTypeId)||defaultWorkTypes.find(x=>x.id===w.workTypeId);return s+Math.min(w.done,w.qty)*(wt?.rate||0)},0);
const nameOf=(employees:Employee[],id:string)=>employees.find(e=>e.id===id)?.name||'-';
const customerName=(customers:string[][],id:string)=>customers.find(c=>c[0]===id)?.[1]||'-';

export function AssignmentsPage({employees,workTypes,customers,assignments,setAssignments}:{employees:Employee[];workTypes:WorkType[];customers:string[][];assignments:Assignment[];setAssignments:React.Dispatch<React.SetStateAction<Assignment[]>>}){
  const [tab,setTab]=useState<'list'|'report'>('list');
  const [showForm,setShowForm]=useState(false);
  const [editId,setEditId]=useState<string|null>(null);
  const [view,setView]=useState<Assignment|null>(null);
  const [toast,setToast]=useState('');
  const [search,setSearch]=useState('');
  const [statusFilter,setStatusFilter]=useState<'All'|Status>('All');
  const [reportEmployee,setReportEmployee]=useState('All');
  const [reportStatus,setReportStatus]=useState<'All'|Status>('All');
  const [reportFrom,setReportFrom]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`});
  const [reportTo,setReportTo]=useState(()=>new Date().toISOString().slice(0,10));
  const [showReportPrint,setShowReportPrint]=useState(false);
  const [menuPos,setMenuPos]=useState<{key:string;x:number;y:number}|null>(null);
  const emptyWork=():AssignmentWork=>({id:'',workTypeId:workTypes.find(w=>w.status==='Active')?.id||workTypes[0]?.id||'',qty:0,done:0});
  const emptyForm=()=>({date:new Date().toISOString().slice(0,10),cuttingNo:'',cuttingQty:0,customerId:customers.find(c=>c[5]==='Active')?.[0]||customers[0]?.[0]||'',employeeId:employees.find(e=>e.status==='Active')?.id||employees[0]?.id||'',works:[emptyWork()],remarks:''});
  const [form,setForm]=useState(emptyForm());
  const activeStaff=employees.filter(e=>e.status==='Active');
  const activeWorkTypes=workTypes.filter(w=>w.status==='Active');
  useEffect(()=>{const close=()=>setMenuPos(null);window.addEventListener('click',close);return()=>window.removeEventListener('click',close)},[]);
  const rows=assignments.filter(a=>{const text=[a.id,a.cuttingNo,nameOf(employees,a.employeeId),customerName(customers,a.customerId),a.remarks].join(' ').toLowerCase();return text.includes(search.toLowerCase())&&(statusFilter==='All'||statusOf(a)===statusFilter)});
  const totalPieces=assignments.reduce((s,a)=>s+workTotal(a),0);
  const donePieces=assignments.reduce((s,a)=>s+workDone(a),0);
  const totalAmount=assignments.reduce((s,a)=>s+workAmount(a,workTypes),0);
  const reportAssignments=assignments.filter(a=>(reportEmployee==='All'||a.employeeId===reportEmployee)&&(reportStatus==='All'||statusOf(a)===reportStatus)&&a.date>=reportFrom&&a.date<=reportTo);
  const reportDone=reportAssignments.reduce((s,a)=>s+workDone(a),0);
  const reportAssigned=reportAssignments.reduce((s,a)=>s+workTotal(a),0);
  const reportEarned=reportAssignments.reduce((s,a)=>s+earnedAmount(a,workTypes),0);
  const openAdd=()=>{setEditId(null);setForm(emptyForm());setShowForm(true)};
  const startEdit=(a:Assignment)=>{setEditId(a.id);setForm({date:a.date,cuttingNo:a.cuttingNo,cuttingQty:a.cuttingQty,customerId:a.customerId||customers[0]?.[0]||'',employeeId:a.employeeId,works:a.works.map(w=>({...w})),remarks:a.remarks});setShowForm(true)};
  const closeForm=()=>{setShowForm(false);setEditId(null);setForm(emptyForm())};
  const setWork=(index:number,changes:Partial<AssignmentWork>)=>setForm(f=>({...f,works:f.works.map((w,i)=>i===index?{...w,...changes}:w)}));
  const save=()=>{if(!form.cuttingNo.trim()){setToast('Enter the cutting no first');setTimeout(()=>setToast(''),2500);return;}if(!form.employeeId){setToast('Select the employee this cutting is assigned to');setTimeout(()=>setToast(''),2500);return;}const works=form.works.map((w,i)=>({id:`W-${i+1}`,workTypeId:w.workTypeId||activeWorkTypes[0]?.id||'',qty:workQty(w,i),done:Number(w.done)||0})).filter(w=>w.workTypeId&&w.qty>0);if(!works.length){setToast('Enter the quantity for the work type below');setTimeout(()=>setToast(''),2500);return;}const assignment={id:editId||`AS-${String(Date.now()).slice(-4)}`,date:form.date,cuttingNo:form.cuttingNo.trim(),cuttingQty:Number(form.cuttingQty)||0,customerId:form.customerId,employeeId:form.employeeId,works,remarks:form.remarks.trim()};if(editId){setAssignments(current=>current.map(a=>a.id===editId?assignment:a))}else{setAssignments(current=>[assignment,...current])}setToast(`${assignment.cuttingNo} ${editId?'updated':'saved'} successfully`);setTimeout(()=>setToast(''),2500);closeForm()};
  const remove=(id:string)=>{const cuttingNo=assignments.find(a=>a.id===id)?.cuttingNo||'Assignment';if(!window.confirm(`Delete ${cuttingNo}?`))return;setAssignments(current=>current.filter(a=>a.id!==id));setToast(`${cuttingNo} deleted`);setTimeout(()=>setToast(''),2500)};
  const ActionMenu=({rowKey,a}:{rowKey:string;a:Assignment})=>{const open=menuPos?.key===rowKey;return <div className="action-menu"><button className="action-menu-btn" title="Actions" onClick={e=>{e.stopPropagation();if(open){setMenuPos(null)}else{const r=(e.currentTarget as HTMLElement).getBoundingClientRect();setMenuPos({key:rowKey,x:Math.min(r.right-132,window.innerWidth-150),y:r.bottom+5})}}}>⋯</button>{open&&<div className="action-menu-drop" style={{left:menuPos.x,top:menuPos.y}} onClick={e=>e.stopPropagation()}><button onClick={()=>{setView(a);setMenuPos(null)}}><Eye size={14}/> View</button><button onClick={()=>{startEdit(a);setMenuPos(null)}}><Pencil size={14}/> Edit</button><button className="danger" onClick={()=>{remove(a.id);setMenuPos(null)}}><Trash2 size={14}/> Delete</button></div>}</div>};
  const workTypeName=(id:string)=>{const wt=workTypes.find(x=>x.id===id)||defaultWorkTypes.find(x=>x.id===id);return wt?`${workTypeCode(wt)} - ${wt.name}`:'-'};
  const workTypeRate=(id:string)=>{const wt=workTypes.find(x=>x.id===id)||defaultWorkTypes.find(x=>x.id===id);return wt?.rate||0};
  const workQty=(w:AssignmentWork,i:number)=>Number(w.qty)||0||(i===0?Number(form.cuttingQty)||0:0);
  const formTotalQty=form.works.reduce((s,w,i)=>s+workQty(w,i),0);
  const formTotalAmount=form.works.reduce((s,w,i)=>s+workQty(w,i)*workTypeRate(w.workTypeId),0);
  const reportDoc=<div className="tax-doc"><h1>CUTTING-WISE WORK REPORT</h1><div className="preview-meta"><span>Period: {reportFrom} to {reportTo}</span><span>{reportAssignments.length} cuttings</span><span>Done: {reportDone} / {reportAssigned} pcs</span><span>Earned: {money(reportEarned)}</span></div><table className="doc-table"><thead><tr><th>CUTTING</th><th>WORK</th><th>WORK TYPE</th><th>DONE / ASSIGNED</th><th>RATE</th><th>EARNED</th><th>STATUS</th></tr></thead><tbody>{reportAssignments.flatMap(a=>a.works.map((w,i)=><tr key={a.id+'-'+i}><td>{i===0?a.cuttingNo:''}</td><td>Work {i+1}</td><td>{workTypeName(w.workTypeId)}</td><td>{Math.min(w.done,w.qty)} / {w.qty}</td><td>{money(workTypeRate(w.workTypeId))}</td><td>{money(Math.min(w.done,w.qty)*workTypeRate(w.workTypeId))}</td><td>{Math.min(w.done,w.qty)>=w.qty?'Completed':'In Progress'}</td></tr>))}</tbody></table><div className="doc-footer"><div><b>Grand total</b><p>{reportDone} / {reportAssigned} pieces • {money(reportEarned)} earned</p></div><div><h3>Authorized Signatory</h3><span>Garment Production ERP</span></div></div></div>;
  return <section className="content">
    <div className="measurement-tabs wage-tabs"><button className={tab==='list'?'active':''} onClick={()=>setTab('list')}><ClipboardList size={16}/><span>Assignments<small>{assignments.length} cuttings</small></span></button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}><BarChart3 size={16}/><span>Cutting-wise Report<small>done / assigned + salary</small></span></button></div>
    {tab==='list'&&<><Stats values={[['Active Assignments',String(assignments.filter(a=>statusOf(a)!=='Completed').length),`${assignments.length} total assignments`],['Pieces Assigned',String(totalPieces),'across all cuttings'],['Pieces Completed',String(donePieces),`${totalPieces?Math.round(donePieces/totalPieces*100):0}% done`],['Work Amount',money(totalAmount),'at master work-type rates']]}/>
    <div className="filterbar salary-filter"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cutting, employee, id"/></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as 'All'|Status)}><option>All</option><option>Pending</option><option>In Progress</option><option>Completed</option></select></label><button className="primary" onClick={openAdd}><Plus size={16}/> New assignment</button></div>
    <Table title="Current assignments" copy="Cutting batches assigned to employees with work type breakdown" headers={['ASSIGNMENT','DATE','CUTTING','CUSTOMER','ASSIGNED TO','CUT QTY','WORKS','DONE','TOTAL','AMOUNT','STATUS']} rows={rows.map(a=>[a.id,a.date,a.cuttingNo,customerName(customers,a.customerId),nameOf(employees,a.employeeId),`${a.cuttingQty} pcs`,a.works.map(w=>workTypeName(w.workTypeId)).join(', '),`${workDone(a)}/${workTotal(a)}`,String(workTotal(a)),money(workAmount(a,workTypes)),statusOf(a)])} actions={r=>{const a=assignments.find(x=>x.id===r[0]);return a?<ActionMenu rowKey={'as-'+a.id} a={a}/>:null}}/>
    {showForm&&<div className="stock-modal-overlay" onClick={closeForm}><article className="card measurement-form entry-modal" onClick={e=>e.stopPropagation()}><div className="form-title"><div><h2>{editId?'Edit assignment':'New work assignment'}</h2><p>Assign a cutting batch to an employee and break it into work types.</p></div><button className="outline" onClick={closeForm}>Close</button></div><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Cutting no<input value={form.cuttingNo} onChange={e=>setForm({...form,cuttingNo:e.target.value})} placeholder="Cutting-1"/></label><label>Cutting quantity<input type="number" min="0" value={form.cuttingQty} onChange={e=>setForm({...form,cuttingQty:Number(e.target.value)})} placeholder="Pieces cut"/></label><label>Customer<select value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}>{customers.map(c=><option value={c[0]} key={c[0]}>{c[1]}</option>)}</select></label><label>Assigned to<select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{activeStaff.length?activeStaff.map(e=><option value={e.id} key={e.id}>{e.name}</option>):employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label className="wide">Remarks<input value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} placeholder="Order, garment or notes"/></label></div><div className="garment-heading"><div><h3>Works in this cutting</h3><p>Each work is a work type with its own quantity. Add as many as needed.</p></div><button className="outline" onClick={()=>setForm(f=>({...f,works:[...f.works,emptyWork()]}))}><Plus size={14}/> Add work</button></div>{form.works.map((w,i)=><div className="form-grid works-row" key={i}><label>Work {i+1} <small>{w.qty>0?money(w.qty*workTypeRate(w.workTypeId)):''}</small><select value={w.workTypeId} onChange={e=>setWork(i,{workTypeId:e.target.value})}>{activeWorkTypes.map(wt=><option value={wt.id} key={wt.id}>{workTypeCode(wt)} - {wt.name} - {money(wt.rate)} / {wt.unit}</option>)}</select></label><label>Quantity<input type="number" min="0" value={w.qty} onChange={e=>setWork(i,{qty:Number(e.target.value)})}/></label><label>Done<input type="number" min="0" value={w.done} onChange={e=>setWork(i,{done:Number(e.target.value)})}/></label>{form.works.length>1&&<button className="mini-remove work-remove" title="Remove" onClick={()=>setForm(f=>({...f,works:f.works.filter((_,x)=>x!==i)}))}>×</button>}</div>)}<div className="form-actions"><div className="summary-total"><span>Total: <strong>{formTotalQty} pcs</strong> • <strong>{money(formTotalAmount)}</strong></span></div><button className="outline" onClick={closeForm}>Cancel</button><button className="primary" onClick={save}><Plus size={15}/> {editId?'Update':'Save'} assignment</button></div></article></div>}
    {view&&<div className="stock-modal-overlay" onClick={()=>setView(null)}><article className="card measurement-form detail-modal" onClick={e=>e.stopPropagation()}><div className="form-title"><div><h2>{view.cuttingNo}</h2><p>Assignment {view.id} • {nameOf(employees,view.employeeId)}</p></div><span className={'status '+statusOf(view).toLowerCase().replace(' ','-')}>{statusOf(view)}</span></div><div className="detail-grid"><div><span>Date</span><strong>{view.date}</strong></div><div><span>Customer</span><strong>{customerName(customers,view.customerId)}</strong></div><div><span>Cutting qty</span><strong>{view.cuttingQty} pcs</strong></div><div><span>Total qty</span><strong>{workTotal(view)} pcs</strong></div><div><span>Completed</span><strong>{workDone(view)} pcs</strong></div><div><span>Amount</span><strong>{money(workAmount(view,workTypes))}</strong></div><div><span>Remarks</span><strong>{view.remarks||'-'}</strong></div></div><div className="works-breakdown">{view.works.map((w,i)=><div key={i}><div className="work-title"><strong>Work {i+1}</strong><span>{workTypeName(w.workTypeId)}</span></div><div className="work-qty"><span>Assigned</span><strong>{w.qty}</strong></div><div className="work-qty"><span>Done</span><strong>{Math.min(w.done,w.qty)}</strong></div><div className="work-qty"><span>Amount</span><strong>{money(w.qty*workTypeRate(w.workTypeId))}</strong></div></div>)}</div><div className="form-actions"><button className="primary" onClick={()=>setView(null)}>Close</button></div></article></div>}
    </>}
    {tab==='report'&&<>
      <div className="filterbar salary-filter no-print"><label>Employee<select value={reportEmployee} onChange={e=>setReportEmployee(e.target.value)}><option value="All">All staff</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Status<select value={reportStatus} onChange={e=>setReportStatus(e.target.value as 'All'|Status)}><option>All</option><option>Pending</option><option>In Progress</option><option>Completed</option></select></label><label>From<input type="date" value={reportFrom} onChange={e=>setReportFrom(e.target.value)}/></label><label>To<input type="date" value={reportTo} onChange={e=>setReportTo(e.target.value)}/></label><button className="outline" onClick={()=>setShowReportPrint(true)}><Printer size={16}/> Print</button></div>
      <div className="report-summary-cards"><div className="report-card blue"><span>Cutting batches</span><strong>{reportAssignments.length}</strong><small>in selected period</small></div><div className="report-card purple"><span>Pieces done</span><strong>{reportDone}</strong><small>{reportDone?Math.round(reportDone/reportAssigned*100):0}% of {reportAssigned} assigned</small></div><div className="report-card green"><span>Earned amount</span><strong>{money(reportEarned)}</strong><small>{reportDone} pcs × work-type rates</small></div></div>
      <article className="card jobs module-table"><div className="cardhead"><div><h2>Cutting-wise work report</h2><p>Each cutting's works with completed / assigned pieces and the earned amount used for salary.</p></div></div><table><thead><tr><th>CUTTING</th><th>WORK</th><th>WORK TYPE</th><th>DONE / ASSIGNED</th><th>RATE</th><th>EARNED</th><th>STATUS</th></tr></thead><tbody>{reportAssignments.map(a=>{const earned=earnedAmount(a,workTypes);return <Fragment key={a.id}><tr className="cutting-head-row"><td colSpan={7}><strong>{a.cuttingNo}</strong><span className="cutting-head-meta">• {customerName(customers,a.customerId)} • {nameOf(employees,a.employeeId)} • {a.date}</span><span className={'status '+statusOf(a).toLowerCase().replace(' ','-')}>{statusOf(a)}</span></td></tr>{a.works.map((w,i)=><tr key={i}><td className="cutting-cell">{i===0?a.cuttingNo:''}</td><td>Work {i+1}</td><td><strong>{workTypeName(w.workTypeId)}</strong></td><td>{Math.min(w.done,w.qty)} / {w.qty}</td><td>{money(workTypeRate(w.workTypeId))}</td><td><strong>{money(Math.min(w.done,w.qty)*workTypeRate(w.workTypeId))}</strong></td><td>{Math.min(w.done,w.qty)>=w.qty?'Completed':'In Progress'}</td></tr>)}<tr className="cutting-total-row"><td colSpan={3}><strong>{a.cuttingNo} total</strong></td><td><strong>{workDone(a)} / {workTotal(a)}</strong></td><td>-</td><td><strong>{money(earned)}</strong></td><td>-</td></tr></Fragment>})}{!reportAssignments.length&&<tr><td colSpan={7}>No assignments found for the selected filters and period.</td></tr>}</tbody><tfoot><tr className="cutting-grand-total"><td colSpan={3}>Grand total</td><td><strong>{reportDone} / {reportAssigned}</strong></td><td>-</td><td><strong>{money(reportEarned)}</strong></td><td>-</td></tr></tfoot></table></article>
    </>}
    {toast&&<div className="toast"><span className="toast-dot"></span>{toast}</div>}
  {showReportPrint&&<PrintPreview doc={reportDoc} onClose={()=>setShowReportPrint(false)}/>}
  </section>
}
